// Datos semilla de 62 proveedores (generado desde PROVEEDORES.xlsx).
// Estos datos se usan como respaldo y para poblar Firestore la primera vez.
export const SEED_PROVEEDORES = [
  {
    "id": 1,
    "nombre": "Opticos de Mexico",
    "giro": "Optica",
    "contacto": "Martin Venegas",
    "telContacto": "871 219 2364",
    "telNegocio": "8711229265",
    "whatsapp": "528712192364",
    "facebook": "https://www.facebook.com/opticosdemexico",
    "instagram": "https://www.instagram.com/opticos_de_mexico/",
    "web": "https://www.opticosdemexico.com/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 2,
    "nombre": "Acqua Laguna",
    "giro": "Maquinas de hielo",
    "contacto": "Roberto Kuri/Mario Argumedo",
    "telContacto": "871 219 5009 / 871 206 1521",
    "telNegocio": "871 206 1521",
    "whatsapp": "528712195009",
    "facebook": "https://www.facebook.com/aqualaguna.torreon/",
    "instagram": "https://www.instagram.com/acqua.laguna/",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 3,
    "nombre": "Nuga Fumigaciones",
    "giro": "Fumigacion",
    "contacto": "Jaime Nuncio",
    "telContacto": "871 471 6374",
    "telNegocio": "8714716374",
    "whatsapp": "528714716374",
    "facebook": "https://www.facebook.com/NUGAFumigaciones/",
    "instagram": "https://www.instagram.com/nuga_fumigaciones/",
    "web": "https://nugafumigaciones.com/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 4,
    "nombre": "Costco de México",
    "giro": "Comercial",
    "contacto": "Oscar Lael",
    "telContacto": "229 436 7456",
    "telNegocio": "(871) 253 0550",
    "whatsapp": "522294367456",
    "facebook": "https://www.facebook.com/CostcoMex/",
    "instagram": "https://www.instagram.com/costco_mexico/",
    "web": "https://www.costco.com.mx/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 5,
    "nombre": "Casa del Vino",
    "giro": "Vinos y Licores",
    "contacto": "Alvaro Ramos",
    "telContacto": "",
    "telNegocio": "871 747 9367",
    "whatsapp": "528717479367",
    "facebook": "https://www.facebook.com/casadelvinomx",
    "instagram": "https://www.instagram.com/casadelvinomx/",
    "web": "https://linktr.ee/LaCasadelvino?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMjU2MjgxMDQwNTU4AAGnRQlkf8L8KHNdFJFCCZ-cPj-WrbB_9JPkFotIsIs95V-iTDw54gYHXLo4iQM_aem_DmOn6maq0uy2aYtAP_tSaQ",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 6,
    "nombre": "API Fumigaciones",
    "giro": "Fumigación",
    "contacto": "Juan Guillen",
    "telContacto": "871 235 2998",
    "telNegocio": "871 235 2998",
    "whatsapp": "528712352998",
    "facebook": "https://www.facebook.com/apifumigacion",
    "instagram": "https://www.instagram.com/apifumigacion/",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 7,
    "nombre": "Ganaderia Revuelta",
    "giro": "Engorda, sacrificio y empaque al vacio de carne de res",
    "contacto": "Rosario Sanchez",
    "telContacto": "871 161 3567",
    "telNegocio": "871 747 4748 / 871 100 4050",
    "whatsapp": "528711613567",
    "facebook": "https://www.facebook.com/ganaderiarevuelta",
    "instagram": "https://www.instagram.com/ganaderia.revuelta",
    "web": "https://www.ganaderiarevuelta.com.mx/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 8,
    "nombre": "Bio Diesel",
    "giro": "Reciclado de Aceite Vegetal Usado",
    "contacto": "Carlos Rodríguez",
    "telContacto": "871 583 8206",
    "telNegocio": "871 583 8206",
    "whatsapp": "528715838206",
    "facebook": "https://www.facebook.com/p/BiodieselLaguna-100057487717725/",
    "instagram": "https://www.instagram.com/biodiesel_laguna/",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 9,
    "nombre": "Promo Plus",
    "giro": "Promocionales y uniformes",
    "contacto": "David Cervantes",
    "telContacto": "871 598 1690",
    "telNegocio": "871 722 5050",
    "whatsapp": "528715981690",
    "facebook": "https://www.facebook.com/PromoPlusArticulos/",
    "instagram": "https://www.instagram.com/promoplus.promocionales/",
    "web": "https://promoplus.mx/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 10,
    "nombre": "Uban Life",
    "giro": "Muebles",
    "contacto": "Huguette Quiñones",
    "telContacto": "871 177 1383",
    "telNegocio": "871 801 1232",
    "whatsapp": "528711771383",
    "facebook": "https://www.facebook.com/urbanlife.mx/",
    "instagram": "https://www.instagram.com/urbanlife.mx/",
    "web": "https://urbanlife.mx/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 11,
    "nombre": "Be Clean",
    "giro": "limpieza y sondeo de trampas de grasa, registros y lavado profesional de tapiceria",
    "contacto": "Melissa Mendez",
    "telContacto": "871 344 9347",
    "telNegocio": "871 140 1042",
    "whatsapp": "528713449347",
    "facebook": "https://www.facebook.com/Becleansolutionsmx/",
    "instagram": "https://www.instagram.com/becleansolutionsmx/",
    "web": "https://www.becleansolutions.mx/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 12,
    "nombre": "La Rancherita",
    "giro": "Tostadas, Tortillas y más",
    "contacto": "Margarita Lozano",
    "telContacto": "871 218 6094",
    "telNegocio": "",
    "whatsapp": "528712186094",
    "facebook": "",
    "instagram": "",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 13,
    "nombre": "Eco-Pack",
    "giro": "Papel grado alimenticio",
    "contacto": "Alan Castelo",
    "telContacto": "465 118 3233",
    "telNegocio": "449-129-0499",
    "whatsapp": "524651183233",
    "facebook": "https://www.facebook.com/p/Eco-Pack-61557059593429/",
    "instagram": "https://www.instagram.com/eco.pack.mx/",
    "web": "https://www.eco-pack.mx/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 14,
    "nombre": "Eventival",
    "giro": "Organización de eventos, venta de boletos, grabado láser, impresión de listones",
    "contacto": "Talia",
    "telContacto": "871 577 5375",
    "telNegocio": "871 577 5375",
    "whatsapp": "528715775375",
    "facebook": "https://www.facebook.com/eventival.mx/",
    "instagram": "https://www.instagram.com/eventival.mx/",
    "web": "https://eventival.mx/Eventos/public/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 15,
    "nombre": "Peek Marketing",
    "giro": "Marketing y Publicidad",
    "contacto": "Veronica Ruiz",
    "telContacto": "871 235 0077",
    "telNegocio": "871 235 0077",
    "whatsapp": "528712350077",
    "facebook": "https://www.facebook.com/PeekAgenciadeMarketing/",
    "instagram": "https://www.instagram.com/peek.marketing/",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 16,
    "nombre": "Mr Green",
    "giro": "Insumos para restaurantes (desechables, abarrotes, materias primas, salsas y más)",
    "contacto": "Veronica Pedroza",
    "telContacto": "871 165 1856",
    "telNegocio": "871 165 1856",
    "whatsapp": "528711651856",
    "facebook": "https://www.facebook.com/MrGreen.Menu.Inteligente/",
    "instagram": "https://www.instagram.com/mrgreentrc/",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 17,
    "nombre": "Maizito Tortilleria",
    "giro": "Tortilleria",
    "contacto": "Deyanira Morales",
    "telContacto": "81 2201 3668",
    "telNegocio": "871 792 2555",
    "whatsapp": "528122013668",
    "facebook": "https://www.facebook.com/elmaizitolaguna/?locale=es_LA",
    "instagram": "https://www.instagram.com/maizitotrc/",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 18,
    "nombre": "Garey",
    "giro": "Surtidora eq de cocina, mobiliario, cubiertos, vajilla, eq menor de cocina",
    "contacto": "Ana Laura Garcia",
    "telContacto": "871 736 2639",
    "telNegocio": "871-718-1477/ 871-718-7677",
    "whatsapp": "528717362639",
    "facebook": "",
    "instagram": "",
    "web": "https://www.grupogarey.com.mx/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 19,
    "nombre": "Recobsa Construcciones",
    "giro": "Topografia, Construccion y Mantenimiento",
    "contacto": "José Manuel Cobos",
    "telContacto": "871 360 9255",
    "telNegocio": "871 360 92 55",
    "whatsapp": "528713609255",
    "facebook": "https://www.facebook.com/p/Recobsa-Construcciones-SA-de-CV-100090507368704/",
    "instagram": "",
    "web": "https://recobsaconstrucciones.com.mx/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 20,
    "nombre": "Little Green",
    "giro": "DISTRIBUIDOR DE FRUTA Y VERDURA GOURMET",
    "contacto": "RICARDO CASTELLANOS",
    "telContacto": "871 328 0792",
    "telNegocio": "8712663797",
    "whatsapp": "528713280792",
    "facebook": "https://www.facebook.com/p/Little-Green-Distribuidor-de-Fruta-y-Verdura-gourmet-Microgreens-100090951584286/",
    "instagram": "https://www.instagram.com/littlegreentrc/",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 21,
    "nombre": "Agua Inmaculada Torreón",
    "giro": "Purificadora de agua (venta de garrafones y botellas personalizadas de agua pur.)",
    "contacto": "Rafael Gómez",
    "telContacto": "871 111 2288",
    "telNegocio": "8711112288",
    "whatsapp": "528711112288",
    "facebook": "https://www.facebook.com/AguaInmaculadaTorreon2/ - https://www.facebook.com/p/Agua-Inmaculada-Senderos-61565384700167/",
    "instagram": "https://www.instagram.com/aguainmaculadatrc/",
    "web": "https://www.aguainmaculada.com/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 22,
    "nombre": "Cava Design & Decor",
    "giro": "Fabricación de artículos para restaurantes y decoración del hogar en madera, acrílico y acero",
    "contacto": "Noelie Cabello",
    "telContacto": "871 727 7017",
    "telNegocio": "871 727 7017",
    "whatsapp": "528717277017",
    "facebook": "https://www.facebook.com/cava.designdecor/",
    "instagram": "https://www.instagram.com/cava.designdecor/",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 23,
    "nombre": "Abastehogar",
    "giro": "Venta de artículos para hogar y restaurante",
    "contacto": "Erika Murillo",
    "telContacto": "871 120 0348",
    "telNegocio": "871 711 0983",
    "whatsapp": "528711200348",
    "facebook": "https://www.facebook.com/profile.php?id=100064404623181",
    "instagram": "https://www.instagram.com/abastehogar/",
    "web": "https://www.abastehogar.com/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 24,
    "nombre": "Fin Wise",
    "giro": "Asesoría financiera",
    "contacto": "Marco Antonio Ibarra",
    "telContacto": "55 4345 8354",
    "telNegocio": "",
    "whatsapp": "525543458354",
    "facebook": "",
    "instagram": "",
    "web": "https://finwise.mx/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 25,
    "nombre": "Maizito Botanas",
    "giro": "Botanas",
    "contacto": "Deyanira Morales",
    "telContacto": "81 2201 3668",
    "telNegocio": "871 392 8682",
    "whatsapp": "528122013668",
    "facebook": "https://www.facebook.com/botanasmaizitomx/",
    "instagram": "https://www.instagram.com/botanasmaizitomx/",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 26,
    "nombre": "El Mariscal",
    "giro": "Comercialización de insumos para foodservice",
    "contacto": "Gael Rosales",
    "telContacto": "871 104 1860",
    "telNegocio": "871 747 9787",
    "whatsapp": "528711041860",
    "facebook": "https://www.facebook.com/ElMariscalPescadosyMariscos/",
    "instagram": "https://www.instagram.com/elmariscalmx/",
    "web": "https://www.elmariscal.mx/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 27,
    "nombre": "Soriana / City club",
    "giro": "",
    "contacto": "Antonio Zamarripa",
    "telContacto": "871 709 2773",
    "telNegocio": "",
    "whatsapp": "528717092773",
    "facebook": "",
    "instagram": "",
    "web": "https://www.soriana.com/ - https://www.cityclub.com.mx/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 28,
    "nombre": "Morenita",
    "giro": "articulos de piel",
    "contacto": "Alejandra Hoyos",
    "telContacto": "871 145 6616",
    "telNegocio": "871 145 6616",
    "whatsapp": "528711456616",
    "facebook": "https://www.facebook.com/morenitaaccesorios/",
    "instagram": "https://www.instagram.com/morenitaaccesorios/",
    "web": "https://morenitaaccesorios.com/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 29,
    "nombre": "Interventas",
    "giro": "Venta de plasticos, biodegradables empaques y deshechables al menudeo",
    "contacto": "Andoni Esquivel",
    "telContacto": "871 189 3032",
    "telNegocio": "8717130198",
    "whatsapp": "528711893032",
    "facebook": "https://www.facebook.com/interventasexpress/",
    "instagram": "https://www.instagram.com/grupointerventas/",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 30,
    "nombre": "Aldape y Asociados",
    "giro": "COMERCIALIZADORA DE EQUIPOS PARA COCINAS",
    "contacto": "María del Socorro González /Beatriz Elizabeth Aldape Arriaga",
    "telContacto": "871 755 9513",
    "telNegocio": "871 189 1921",
    "whatsapp": "528717559513",
    "facebook": "https://www.facebook.com/AldapeyAsociadosSAdeCV/",
    "instagram": "https://www.instagram.com/aldapeyasocia2/",
    "web": "https://www.aldape.vip/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 31,
    "nombre": "Zesati Internacional",
    "giro": "Servicios profesionales a empresas",
    "contacto": "Luis Arratia",
    "telContacto": "871 240 2158",
    "telNegocio": "871 688 1272",
    "whatsapp": "528712402158",
    "facebook": "https://www.facebook.com/zesatiinternacional/?locale=es_LA",
    "instagram": "https://www.instagram.com/zesatiinternacional/",
    "web": "https://zesatiinternacional.com/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 32,
    "nombre": "Montaña Food Service",
    "giro": "Comercializacion de carne de res, ave, puerco y otras proteinas",
    "contacto": "Javier Montaña",
    "telContacto": "664 375 4637",
    "telNegocio": "",
    "whatsapp": "526643754637",
    "facebook": "",
    "instagram": "https://www.instagram.com/jmontanav/",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 33,
    "nombre": "Gafi",
    "giro": "Comercio al por mayor de abarrotes",
    "contacto": "ALEJANDRO ZORRILLA",
    "telContacto": "871 178 7580",
    "telNegocio": "871 747 4645",
    "whatsapp": "528711787580",
    "facebook": "",
    "instagram": "",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 34,
    "nombre": "Frutiagua",
    "giro": "Comercializacion de aguas frescas embotelladas",
    "contacto": "Raul de Alba",
    "telContacto": "871 225 0611",
    "telNegocio": "871 225 0611",
    "whatsapp": "528712250611",
    "facebook": "https://www.facebook.com/fruitiagua/",
    "instagram": "",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 35,
    "nombre": "Bella Napoli El Sabino",
    "giro": "Comercializadora de insumos lacteos y derivados",
    "contacto": "Daniel Baca",
    "telContacto": "871 173 4169",
    "telNegocio": "",
    "whatsapp": "528711734169",
    "facebook": "",
    "instagram": "",
    "web": "https://elsabino.com.mx/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 36,
    "nombre": "Catorce 30 Comercializadora",
    "giro": "comercio al por mayor",
    "contacto": "Alberto Delgado/Alejandra Reed",
    "telContacto": "443 410 1198 / 871 845 8770",
    "telNegocio": "871 676 4754",
    "whatsapp": "524434101198",
    "facebook": "https://www.facebook.com/catorce30/",
    "instagram": "https://www.instagram.com/catorce30/",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 37,
    "nombre": "Forticlean",
    "giro": "Fabricación y distribución de productos de limpieza",
    "contacto": "José Guerrero",
    "telContacto": "871 104 3889",
    "telNegocio": "871 736 2478",
    "whatsapp": "528711043889",
    "facebook": "https://www.facebook.com/Forticlean",
    "instagram": "https://www.instagram.com/forticlean_trc/",
    "web": "https://forticlean.mx/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 38,
    "nombre": "Mavesa de la Laguna",
    "giro": "Abarrotes",
    "contacto": "Sofia Gomez",
    "telContacto": "871 149 8119",
    "telNegocio": "871 717 3032",
    "whatsapp": "528711498119",
    "facebook": "https://www.facebook.com/p/Mavesa-De-La-Laguna-100064714941133/",
    "instagram": "https://www.instagram.com/mavesalaguna/",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 39,
    "nombre": "GHC Industrial / Equipo de Proteccion personal alimenticio",
    "giro": "Equipo de proteccion personal alimenticio",
    "contacto": "Ema Castillo",
    "telContacto": "871 972 4199",
    "telNegocio": "871 972 6660",
    "whatsapp": "528719724199",
    "facebook": "https://www.facebook.com/p/GHC-industrial-l-Expertos-en-equipo-de-protecci%C3%B3n-personal-61558259930230/",
    "instagram": "https://www.instagram.com/ghcindustrial_/",
    "web": "https://ghcindustrial.mx/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 40,
    "nombre": "Grupo Modelo",
    "giro": "Distribuidora",
    "contacto": "Valeria Torres",
    "telContacto": "871 161 3282",
    "telNegocio": "",
    "whatsapp": "528711613282",
    "facebook": "https://www.facebook.com/GrupoModeloMX/?_rdr",
    "instagram": "",
    "web": "https://www.grupomodelo.com/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 41,
    "nombre": "Mr Sabor",
    "giro": "Alimentos",
    "contacto": "Andrea Enriquez",
    "telContacto": "871 233 1892",
    "telNegocio": "871 233 9594",
    "whatsapp": "528712331892",
    "facebook": "https://www.facebook.com/mrsabormx",
    "instagram": "https://www.instagram.com/mrsabor.mx/",
    "web": "https://mrsabor.mx/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 42,
    "nombre": "Risanti",
    "giro": "Mobiliario",
    "contacto": "Ricardo Santibañez",
    "telContacto": "871 734 5191",
    "telNegocio": "871 563 5961",
    "whatsapp": "528717345191",
    "facebook": "https://www.facebook.com/risantimx/",
    "instagram": "https://www.instagram.com/risantimx/",
    "web": "https://www.risanti.mx/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 43,
    "nombre": "Sercom",
    "giro": "Mantenimiento en general",
    "contacto": "Erick Recendiz",
    "telContacto": "871 348 2812",
    "telNegocio": "871 482 1252",
    "whatsapp": "528713482812",
    "facebook": "https://www.facebook.com/Sercomlaguna/",
    "instagram": "https://www.instagram.com/sercomlaguna/",
    "web": "https://www.sercomlaguna.com/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 44,
    "nombre": "Bioclean Lavanderia",
    "giro": "LAVANDERIA, PLANCHADURIA, TINTORERIA Y MÁS",
    "contacto": "CECILIA MARTINEZ",
    "telContacto": "871 113 6508",
    "telNegocio": "871 267 4812",
    "whatsapp": "528711136508",
    "facebook": "https://www.facebook.com/BioCleanLaundryTRC/",
    "instagram": "https://www.instagram.com/biocleanlavanderiatrc/",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 45,
    "nombre": "Paalsa",
    "giro": "Comercializacion y Distribucion de HVAC (Minisplit, Fan & Coil, Cassette, Piso Techo, VRF Y Chiller.",
    "contacto": "Carlos Alberto Almazan",
    "telContacto": "871 143 6521",
    "telNegocio": "871 980 4136",
    "whatsapp": "528711436521",
    "facebook": "https://www.facebook.com/PAALSATORREON/",
    "instagram": "https://www.instagram.com/paalsa.mx/",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 46,
    "nombre": "Mercahorro",
    "giro": "Construcción de Inmuebles comerciales, institucionales y de servicios.",
    "contacto": "Alejandro Gayosso",
    "telContacto": "81 2000 8044",
    "telNegocio": "",
    "whatsapp": "528120008044",
    "facebook": "https://www.facebook.com/mercadosmercahorro",
    "instagram": "https://www.instagram.com/mercahorroabastos/",
    "web": "https://www.mercahorro.com.mx/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 47,
    "nombre": "Tortilleria Doña Toña",
    "giro": "Tortilleria",
    "contacto": "Francisco Javier Nava",
    "telContacto": "871 177 4032",
    "telNegocio": "871 713 7101",
    "whatsapp": "528711774032",
    "facebook": "https://www.facebook.com/tortilleria.donatona/",
    "instagram": "https://www.instagram.com/tortilleriadonatona/",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 48,
    "nombre": "RM Servicios de limpieza",
    "giro": "Servicio de Limpieza",
    "contacto": "Mari Amada Fernandez",
    "telContacto": "871 156 0549",
    "telNegocio": "871 234 6249",
    "whatsapp": "528711560549",
    "facebook": "https://www.facebook.com/p/RM-Servicios-de-Limpieza-100039883329734/",
    "instagram": "https://www.instagram.com/rm_serviciosdelimpieza/",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 49,
    "nombre": "Cerveceria Santo Negro",
    "giro": "Cerveza artesanal",
    "contacto": "Natalia Wolf",
    "telContacto": "614 223 9289",
    "telNegocio": "614 223 9289",
    "whatsapp": "526142239289",
    "facebook": "https://www.facebook.com/santonegrowb",
    "instagram": "https://www.instagram.com/cerveceriasantonegro.wb/",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 50,
    "nombre": "Liisto",
    "giro": "Software punto de venta",
    "contacto": "Karla Real",
    "telContacto": "33 1517 5065",
    "telNegocio": "",
    "whatsapp": "523315175065",
    "facebook": "",
    "instagram": "https://www.instagram.com/liisto_digital",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 51,
    "nombre": "Publicidad 23",
    "giro": "Impresión de formas continuas y otros impresos",
    "contacto": "Daniel Ibarra",
    "telContacto": "618 223 7714",
    "telNegocio": "8715037389 / 8714134119",
    "whatsapp": "526182237714",
    "facebook": "https://www.facebook.com/p/23-Publicidad-Torre%C3%B3n-61580824210566/",
    "instagram": "https://www.instagram.com/23.publicidad/",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 52,
    "nombre": "Alba",
    "giro": "comercializadora",
    "contacto": "Gustavo Morales / Arturo Romero",
    "telContacto": "7871 156 4072/871 185 5936",
    "telNegocio": "871 723 0077",
    "whatsapp": "528711564072",
    "facebook": "https://www.facebook.com/p/ALBA-Comercializadora-61559891912397/ - https://www.facebook.com/ALBALacteos/",
    "instagram": "https://www.instagram.com/alba.comercializadora/",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 53,
    "nombre": "Sistemas contra incendios de la Laguna",
    "giro": "Seguridad, Extintores, Alarmas contra incendios, Recarga de extintores, Redes contra incendios y Señaletica.",
    "contacto": "Miguel Izaguirre",
    "telContacto": "871 786 3681",
    "telNegocio": "871 721 1684",
    "whatsapp": "528717863681",
    "facebook": "https://www.facebook.com/sistemascontraincendiosdelalaguna",
    "instagram": "https://www.instagram.com/sistemas_scil/",
    "web": "https://www.extintores-scil.com/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 54,
    "nombre": "Diseña Tu Imagen solucion en uniformes",
    "giro": "Uniformes",
    "contacto": "Emelia Govela, Fatima Dipp",
    "telContacto": "871 799 9593 / 871 143 7813",
    "telNegocio": "8711437813",
    "whatsapp": "528717999593",
    "facebook": "https://www.facebook.com/p/Dise%C3%B1a-tu-Imagen-100063646017245/",
    "instagram": "https://www.instagram.com/disena_tu_imagen/",
    "web": "https://disenatuimagen.mx/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 55,
    "nombre": "Easy Tap",
    "giro": "Creacion de sitios web, desarrollo de apps con IA",
    "contacto": "Israel Torres",
    "telContacto": "8719676251",
    "telNegocio": "8719676251",
    "whatsapp": "528719676251",
    "facebook": "",
    "instagram": "",
    "web": "https://www.instagram.com/easytaptrc/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 56,
    "nombre": "Cafelaria",
    "giro": "Comercializacion de Insumos para Cafeterias y Restaurantes.",
    "contacto": "Luis Lopez",
    "telContacto": "8711091985",
    "telNegocio": "8711091985",
    "whatsapp": "528711091985",
    "facebook": "https://www.facebook.com/cafelaria.insumos/",
    "instagram": "https://www.instagram.com/cafelaria.insumos/",
    "web": "https://cafelaria.com.mx/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 57,
    "nombre": "Purifika",
    "giro": "Soluciones en agua purificada.",
    "contacto": "Carlos Cordova",
    "telContacto": "8717931742",
    "telNegocio": "8717931742",
    "whatsapp": "528717931742",
    "facebook": "https://www.instagram.com/purifikafranquicias/",
    "instagram": "https://www.facebook.com/purifikalaguna/",
    "web": "https://purifika.com/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 58,
    "nombre": "Sotol Spirits",
    "giro": "Destilería/producción de bebidas alcohólicas",
    "contacto": "Ramón Castro Antonio Parada",
    "telContacto": "871 520 0427",
    "telNegocio": "871 298 4735",
    "whatsapp": "528715200427",
    "facebook": "https://www.facebook.com/profile.php?id=61554726833483&locale=af_ZA#",
    "instagram": "https://www.instagram.com/sotolthebotica/",
    "web": "https://www.sotolspirits.com/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 59,
    "nombre": "Deselci",
    "giro": "Mantenimiento y construcción",
    "contacto": "Jonathan Guevara",
    "telContacto": "8711207661",
    "telNegocio": "8711888991",
    "whatsapp": "528711207661",
    "facebook": "",
    "instagram": "",
    "web": "https://www.deselci.com/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 60,
    "nombre": "Recibelo link. Sandby",
    "giro": "Tecnología, comercio digital y logística para restaurantes.",
    "contacto": "Santiago Garrido",
    "telContacto": "8717362263",
    "telNegocio": "8715801209",
    "whatsapp": "528717362263",
    "facebook": "https://www.facebook.com/people/Recibelolink/61580642576438/",
    "instagram": "https://www.instagram.com/recibelo.link/",
    "web": "https://recibelo.link/",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 61,
    "nombre": "Rumal",
    "giro": "Manejo de residuos solidos Urbanos",
    "contacto": "José Abraham Ruvalcaba",
    "telContacto": "871 275 1493",
    "telNegocio": "871 410 7649",
    "whatsapp": "528712751493",
    "facebook": "https://www.facebook.com/p/Recolecci%C3%B3n-de-residuos-y-reciclaje-Rumal-61556685146932/",
    "instagram": "",
    "web": "",
    "fotos": [],
    "descripcion": ""
  },
  {
    "id": 62,
    "nombre": "Charly Express",
    "giro": "Limpieza",
    "contacto": "CARLOS ECHAVARRIA DE SANTIAGO",
    "telContacto": "8711979561",
    "telNegocio": "8711979561",
    "whatsapp": "528711979561",
    "facebook": "https://www.facebook.com/p/Charly-Express-100063580993418/?locale=es_LA",
    "instagram": "https://www.instagram.com/charly_express71/",
    "web": "",
    "fotos": [],
    "descripcion": ""
  }
];

// Contenido por defecto del inicio (carrusel, video, textos). Editable desde el panel admin.
export const DEFAULT_SITE = {
  hero: {
    titulo: "CANIRAC LAGUNA",
    subtitulo: "Cámara Nacional de la Industria de Restaurantes y Alimentos Condimentados"
  },
  carousel: [
    // Ejemplos con imágenes de muestra; reemplázalas en el panel de administración.
    { url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&q=70", titulo: "Bienvenido a CANIRAC Laguna" },
    { url: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=70", titulo: "Unidos por la industria restaurantera" },
    { url: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=1200&q=70", titulo: "Proveedores confiables para tu negocio" }
  ],
  video: {
    // Puede ser un enlace de YouTube o un enlace directo .mp4
    url: "",
    titulo: "Conoce CANIRAC Laguna"
  },
  textos: {
    proveedoresIntro: "Directorio oficial de proveedores CANIRAC Laguna. Encuentra el aliado ideal para tu restaurante."
  }
};
